#!/usr/bin/env bash
[[ " help cleaner:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | cleaner:help)
    help_content_func () {
      declare desc="return cleaner plugin help content"
      cat<<help_content
    cleaner:enable <name>, Enable cleaner for app
    cleaner:disable <name>, Disable cleaner for app
help_content
    }

    if [[ $1 = "cleaner:help" ]] ; then
        echo -e 'Usage: dokku cleaner[:COMMAND]'
        echo ''
        echo 'Clean old processes (for example sidekiq) via post-deploy hook.'
        echo ''
        echo 'Additional commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  cleaner:enable)
    echo "ACTIVE" > "$DOKKU_ROOT/$APP/DEPLOY_CLEANER"
    echo "-----> Clean after deployment enabled for $2"
    ;;
  cleaner:disable)
    echo "-----> Clean after deployment disabled for $2"
    rm "$DOKKU_ROOT/$APP/DEPLOY_CLEANER"
   ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
